matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
      script:
        - mkdir binhouse
        - IMAGE=quay.io/pypa/manylinux2010_x86_64
        - docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) -i $IMAGE ./build.sh
        - mv binhouse/hmmsearch binhouse/hmmsearch_manylinux2010_x86_64
    - os: osx
      language: c
      compiler: clang
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.9
        - ARCHFLAGS="-arch x86_64"
      script:
        - mkdir binhouse
        - ./build.sh
        - mv binhouse/hmmsearch binhouse/hmmsearch_macosx_10_9_x86_64
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
