matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
install:
  - pwd
script:
  - mkdir binhouse
  - IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) -i $IMAGE "/bin/bash build_on_linux.sh"
  # - docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) -i $IMAGE "pwd; ls"
  - docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) -i $IMAGE /$(basename $(pwd))/build_on_linux.sh
  - ls binhouse
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
